version: "3"
services:
  app:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
    environment:
      TZ: Asia/Tokyo
